namespace TownOfUs
{
    public enum CustomRPC
    {
        SetJester = 43,
        SetCouple,
        SetMayor,
        SetSheriff,
        SetEngineer,
        SetSwapper,
        SetShifter,
        SetInvestigator,
        SetTimeLord,
        SetMedic,
        SetSeer,
        SetMorphling,
        SetCamouflager,
        SetExecutioner,
        SetTarget,
        SetSpy,
        SetSnitch,
        SetMiner,
        SetSwooper,
        SetJanitor,
        SetArsonist,
        SetAltruist,
        SetUndertaker,
        SetAssassin,
        SetUnderdog,

        SetTorch,
        SetDiseased,
        SetFlash,
        SetTiebreaker,
        SetDrunk,
        SetBigBoi,
        SetButtonBarry,

        SetPhantom,
        PhantomDied,
        CatchPhantom,

        SetCrewmate,
        SetImpostor,


        LoveWin,
        GlitchWin,
        ArsonistWin,
        PhantomWin,
        JesterLose,
        ExecutionerLose,
        ShifterLose,
        GlitchLose,
        ArsonistLose,
        NobodyWins,
        PhantomLose,

        JanitorClean,
        EngineerFix,
        SetExtraVotes,
        SetSwaps,
        Shift,
        Protect,
        AttemptSound,
        Investigate,
        Rewind,
        RewindRevive,
        Morph,
        Camouflage,
        UnCamouflage,
        Mine,
        Swoop,
        UnSwoop,
        Douse,
        Ignite,
        AltruistRevive,
        BarryButton,
        Drag,
        Drop,
        AssassinKill,

        SetGlitch,
        BypassKill,
        SetMimic,
        ResetAnim,
        SetHacked,

        Start,
        SyncCustomSettings,
        FixAnimation,
        
        AddMayorVoteBank
    }
}
